// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Products.proto

package eshop.api.product;

public final class Products {
  private Products() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eshop.api.product.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string vendorId = 2;</code>
     */
    java.lang.String getVendorId();
    /**
     * <code>string vendorId = 2;</code>
     */
    com.google.protobuf.ByteString
        getVendorIdBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>repeated string tags = 5;</code>
     */
    java.util.List<java.lang.String>
        getTagsList();
    /**
     * <code>repeated string tags = 5;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated string tags = 5;</code>
     */
    java.lang.String getTags(int index);
    /**
     * <code>repeated string tags = 5;</code>
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);

    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    java.util.List<eshop.api.product.Products.ProductSubType> 
        getSubTypesList();
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    eshop.api.product.Products.ProductSubType getSubTypes(int index);
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    int getSubTypesCount();
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    java.util.List<? extends eshop.api.product.Products.ProductSubTypeOrBuilder> 
        getSubTypesOrBuilderList();
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    eshop.api.product.Products.ProductSubTypeOrBuilder getSubTypesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code eshop.api.product.Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eshop.api.product.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      id_ = "";
      vendorId_ = "";
      name_ = "";
      desc_ = "";
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      subTypes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              vendorId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                tags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              tags_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                subTypes_ = new java.util.ArrayList<eshop.api.product.Products.ProductSubType>();
                mutable_bitField0_ |= 0x00000020;
              }
              subTypes_.add(
                  input.readMessage(eshop.api.product.Products.ProductSubType.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          tags_ = tags_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          subTypes_ = java.util.Collections.unmodifiableList(subTypes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eshop.api.product.Products.internal_static_eshop_api_product_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eshop.api.product.Products.internal_static_eshop_api_product_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eshop.api.product.Products.Product.class, eshop.api.product.Products.Product.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VENDORID_FIELD_NUMBER = 2;
    private volatile java.lang.Object vendorId_;
    /**
     * <code>string vendorId = 2;</code>
     */
    public java.lang.String getVendorId() {
      java.lang.Object ref = vendorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendorId_ = s;
        return s;
      }
    }
    /**
     * <code>string vendorId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVendorIdBytes() {
      java.lang.Object ref = vendorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList tags_;
    /**
     * <code>repeated string tags = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated string tags = 5;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 5;</code>
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    public static final int SUBTYPES_FIELD_NUMBER = 6;
    private java.util.List<eshop.api.product.Products.ProductSubType> subTypes_;
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    public java.util.List<eshop.api.product.Products.ProductSubType> getSubTypesList() {
      return subTypes_;
    }
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    public java.util.List<? extends eshop.api.product.Products.ProductSubTypeOrBuilder> 
        getSubTypesOrBuilderList() {
      return subTypes_;
    }
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    public int getSubTypesCount() {
      return subTypes_.size();
    }
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    public eshop.api.product.Products.ProductSubType getSubTypes(int index) {
      return subTypes_.get(index);
    }
    /**
     * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
     */
    public eshop.api.product.Products.ProductSubTypeOrBuilder getSubTypesOrBuilder(
        int index) {
      return subTypes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getVendorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vendorId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tags_.getRaw(i));
      }
      for (int i = 0; i < subTypes_.size(); i++) {
        output.writeMessage(6, subTypes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getVendorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vendorId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += computeStringSizeNoTag(tags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      for (int i = 0; i < subTypes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, subTypes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eshop.api.product.Products.Product)) {
        return super.equals(obj);
      }
      eshop.api.product.Products.Product other = (eshop.api.product.Products.Product) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getVendorId()
          .equals(other.getVendorId());
      result = result && getName()
          .equals(other.getName());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && getTagsList()
          .equals(other.getTagsList());
      result = result && getSubTypesList()
          .equals(other.getSubTypesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + VENDORID_FIELD_NUMBER;
      hash = (53 * hash) + getVendorId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      if (getSubTypesCount() > 0) {
        hash = (37 * hash) + SUBTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getSubTypesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eshop.api.product.Products.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Products.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Products.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eshop.api.product.Products.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eshop.api.product.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eshop.api.product.Product)
        eshop.api.product.Products.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eshop.api.product.Products.internal_static_eshop_api_product_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eshop.api.product.Products.internal_static_eshop_api_product_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eshop.api.product.Products.Product.class, eshop.api.product.Products.Product.Builder.class);
      }

      // Construct using eshop.api.product.Products.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubTypesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        vendorId_ = "";

        name_ = "";

        desc_ = "";

        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (subTypesBuilder_ == null) {
          subTypes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          subTypesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eshop.api.product.Products.internal_static_eshop_api_product_Product_descriptor;
      }

      @java.lang.Override
      public eshop.api.product.Products.Product getDefaultInstanceForType() {
        return eshop.api.product.Products.Product.getDefaultInstance();
      }

      @java.lang.Override
      public eshop.api.product.Products.Product build() {
        eshop.api.product.Products.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eshop.api.product.Products.Product buildPartial() {
        eshop.api.product.Products.Product result = new eshop.api.product.Products.Product(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.vendorId_ = vendorId_;
        result.name_ = name_;
        result.desc_ = desc_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          tags_ = tags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.tags_ = tags_;
        if (subTypesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            subTypes_ = java.util.Collections.unmodifiableList(subTypes_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.subTypes_ = subTypes_;
        } else {
          result.subTypes_ = subTypesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eshop.api.product.Products.Product) {
          return mergeFrom((eshop.api.product.Products.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eshop.api.product.Products.Product other) {
        if (other == eshop.api.product.Products.Product.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getVendorId().isEmpty()) {
          vendorId_ = other.vendorId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (subTypesBuilder_ == null) {
          if (!other.subTypes_.isEmpty()) {
            if (subTypes_.isEmpty()) {
              subTypes_ = other.subTypes_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureSubTypesIsMutable();
              subTypes_.addAll(other.subTypes_);
            }
            onChanged();
          }
        } else {
          if (!other.subTypes_.isEmpty()) {
            if (subTypesBuilder_.isEmpty()) {
              subTypesBuilder_.dispose();
              subTypesBuilder_ = null;
              subTypes_ = other.subTypes_;
              bitField0_ = (bitField0_ & ~0x00000020);
              subTypesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubTypesFieldBuilder() : null;
            } else {
              subTypesBuilder_.addAllMessages(other.subTypes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eshop.api.product.Products.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eshop.api.product.Products.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vendorId_ = "";
      /**
       * <code>string vendorId = 2;</code>
       */
      public java.lang.String getVendorId() {
        java.lang.Object ref = vendorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vendorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vendorId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVendorIdBytes() {
        java.lang.Object ref = vendorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vendorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vendorId = 2;</code>
       */
      public Builder setVendorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vendorId = 2;</code>
       */
      public Builder clearVendorId() {
        
        vendorId_ = getDefaultInstance().getVendorId();
        onChanged();
        return this;
      }
      /**
       * <code>string vendorId = 2;</code>
       */
      public Builder setVendorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vendorId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTagsList() {
        return tags_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public java.lang.String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public Builder setTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public Builder addTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public Builder clearTags() {
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 5;</code>
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<eshop.api.product.Products.ProductSubType> subTypes_ =
        java.util.Collections.emptyList();
      private void ensureSubTypesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          subTypes_ = new java.util.ArrayList<eshop.api.product.Products.ProductSubType>(subTypes_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          eshop.api.product.Products.ProductSubType, eshop.api.product.Products.ProductSubType.Builder, eshop.api.product.Products.ProductSubTypeOrBuilder> subTypesBuilder_;

      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public java.util.List<eshop.api.product.Products.ProductSubType> getSubTypesList() {
        if (subTypesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subTypes_);
        } else {
          return subTypesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public int getSubTypesCount() {
        if (subTypesBuilder_ == null) {
          return subTypes_.size();
        } else {
          return subTypesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public eshop.api.product.Products.ProductSubType getSubTypes(int index) {
        if (subTypesBuilder_ == null) {
          return subTypes_.get(index);
        } else {
          return subTypesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder setSubTypes(
          int index, eshop.api.product.Products.ProductSubType value) {
        if (subTypesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTypesIsMutable();
          subTypes_.set(index, value);
          onChanged();
        } else {
          subTypesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder setSubTypes(
          int index, eshop.api.product.Products.ProductSubType.Builder builderForValue) {
        if (subTypesBuilder_ == null) {
          ensureSubTypesIsMutable();
          subTypes_.set(index, builderForValue.build());
          onChanged();
        } else {
          subTypesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder addSubTypes(eshop.api.product.Products.ProductSubType value) {
        if (subTypesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTypesIsMutable();
          subTypes_.add(value);
          onChanged();
        } else {
          subTypesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder addSubTypes(
          int index, eshop.api.product.Products.ProductSubType value) {
        if (subTypesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubTypesIsMutable();
          subTypes_.add(index, value);
          onChanged();
        } else {
          subTypesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder addSubTypes(
          eshop.api.product.Products.ProductSubType.Builder builderForValue) {
        if (subTypesBuilder_ == null) {
          ensureSubTypesIsMutable();
          subTypes_.add(builderForValue.build());
          onChanged();
        } else {
          subTypesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder addSubTypes(
          int index, eshop.api.product.Products.ProductSubType.Builder builderForValue) {
        if (subTypesBuilder_ == null) {
          ensureSubTypesIsMutable();
          subTypes_.add(index, builderForValue.build());
          onChanged();
        } else {
          subTypesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder addAllSubTypes(
          java.lang.Iterable<? extends eshop.api.product.Products.ProductSubType> values) {
        if (subTypesBuilder_ == null) {
          ensureSubTypesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subTypes_);
          onChanged();
        } else {
          subTypesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder clearSubTypes() {
        if (subTypesBuilder_ == null) {
          subTypes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          subTypesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public Builder removeSubTypes(int index) {
        if (subTypesBuilder_ == null) {
          ensureSubTypesIsMutable();
          subTypes_.remove(index);
          onChanged();
        } else {
          subTypesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public eshop.api.product.Products.ProductSubType.Builder getSubTypesBuilder(
          int index) {
        return getSubTypesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public eshop.api.product.Products.ProductSubTypeOrBuilder getSubTypesOrBuilder(
          int index) {
        if (subTypesBuilder_ == null) {
          return subTypes_.get(index);  } else {
          return subTypesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public java.util.List<? extends eshop.api.product.Products.ProductSubTypeOrBuilder> 
           getSubTypesOrBuilderList() {
        if (subTypesBuilder_ != null) {
          return subTypesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subTypes_);
        }
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public eshop.api.product.Products.ProductSubType.Builder addSubTypesBuilder() {
        return getSubTypesFieldBuilder().addBuilder(
            eshop.api.product.Products.ProductSubType.getDefaultInstance());
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public eshop.api.product.Products.ProductSubType.Builder addSubTypesBuilder(
          int index) {
        return getSubTypesFieldBuilder().addBuilder(
            index, eshop.api.product.Products.ProductSubType.getDefaultInstance());
      }
      /**
       * <code>repeated .eshop.api.product.ProductSubType subTypes = 6;</code>
       */
      public java.util.List<eshop.api.product.Products.ProductSubType.Builder> 
           getSubTypesBuilderList() {
        return getSubTypesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          eshop.api.product.Products.ProductSubType, eshop.api.product.Products.ProductSubType.Builder, eshop.api.product.Products.ProductSubTypeOrBuilder> 
          getSubTypesFieldBuilder() {
        if (subTypesBuilder_ == null) {
          subTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              eshop.api.product.Products.ProductSubType, eshop.api.product.Products.ProductSubType.Builder, eshop.api.product.Products.ProductSubTypeOrBuilder>(
                  subTypes_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          subTypes_ = null;
        }
        return subTypesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eshop.api.product.Product)
    }

    // @@protoc_insertion_point(class_scope:eshop.api.product.Product)
    private static final eshop.api.product.Products.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eshop.api.product.Products.Product();
    }

    public static eshop.api.product.Products.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eshop.api.product.Products.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductSubTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eshop.api.product.ProductSubType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string productId = 2;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>string productId = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    java.util.List<java.lang.String>
        getImgUrlsList();
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    int getImgUrlsCount();
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    java.lang.String getImgUrls(int index);
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    com.google.protobuf.ByteString
        getImgUrlsBytes(int index);
  }
  /**
   * Protobuf type {@code eshop.api.product.ProductSubType}
   */
  public  static final class ProductSubType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eshop.api.product.ProductSubType)
      ProductSubTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductSubType.newBuilder() to construct.
    private ProductSubType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductSubType() {
      id_ = "";
      productId_ = "";
      name_ = "";
      desc_ = "";
      imgUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductSubType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                imgUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              imgUrls_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          imgUrls_ = imgUrls_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eshop.api.product.Products.internal_static_eshop_api_product_ProductSubType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eshop.api.product.Products.internal_static_eshop_api_product_ProductSubType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eshop.api.product.Products.ProductSubType.class, eshop.api.product.Products.ProductSubType.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object productId_;
    /**
     * <code>string productId = 2;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string productId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMGURLS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList imgUrls_;
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getImgUrlsList() {
      return imgUrls_;
    }
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    public int getImgUrlsCount() {
      return imgUrls_.size();
    }
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    public java.lang.String getImgUrls(int index) {
      return imgUrls_.get(index);
    }
    /**
     * <code>repeated string imgUrls = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImgUrlsBytes(int index) {
      return imgUrls_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      for (int i = 0; i < imgUrls_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, imgUrls_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < imgUrls_.size(); i++) {
          dataSize += computeStringSizeNoTag(imgUrls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImgUrlsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eshop.api.product.Products.ProductSubType)) {
        return super.equals(obj);
      }
      eshop.api.product.Products.ProductSubType other = (eshop.api.product.Products.ProductSubType) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && getName()
          .equals(other.getName());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && getImgUrlsList()
          .equals(other.getImgUrlsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (getImgUrlsCount() > 0) {
        hash = (37 * hash) + IMGURLS_FIELD_NUMBER;
        hash = (53 * hash) + getImgUrlsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eshop.api.product.Products.ProductSubType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Products.ProductSubType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.ProductSubType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Products.ProductSubType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eshop.api.product.Products.ProductSubType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eshop.api.product.ProductSubType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eshop.api.product.ProductSubType)
        eshop.api.product.Products.ProductSubTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eshop.api.product.Products.internal_static_eshop_api_product_ProductSubType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eshop.api.product.Products.internal_static_eshop_api_product_ProductSubType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eshop.api.product.Products.ProductSubType.class, eshop.api.product.Products.ProductSubType.Builder.class);
      }

      // Construct using eshop.api.product.Products.ProductSubType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        productId_ = "";

        name_ = "";

        desc_ = "";

        imgUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eshop.api.product.Products.internal_static_eshop_api_product_ProductSubType_descriptor;
      }

      @java.lang.Override
      public eshop.api.product.Products.ProductSubType getDefaultInstanceForType() {
        return eshop.api.product.Products.ProductSubType.getDefaultInstance();
      }

      @java.lang.Override
      public eshop.api.product.Products.ProductSubType build() {
        eshop.api.product.Products.ProductSubType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eshop.api.product.Products.ProductSubType buildPartial() {
        eshop.api.product.Products.ProductSubType result = new eshop.api.product.Products.ProductSubType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.productId_ = productId_;
        result.name_ = name_;
        result.desc_ = desc_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          imgUrls_ = imgUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.imgUrls_ = imgUrls_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eshop.api.product.Products.ProductSubType) {
          return mergeFrom((eshop.api.product.Products.ProductSubType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eshop.api.product.Products.ProductSubType other) {
        if (other == eshop.api.product.Products.ProductSubType.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.imgUrls_.isEmpty()) {
          if (imgUrls_.isEmpty()) {
            imgUrls_ = other.imgUrls_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureImgUrlsIsMutable();
            imgUrls_.addAll(other.imgUrls_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eshop.api.product.Products.ProductSubType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eshop.api.product.Products.ProductSubType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string productId = 2;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList imgUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImgUrlsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          imgUrls_ = new com.google.protobuf.LazyStringArrayList(imgUrls_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getImgUrlsList() {
        return imgUrls_.getUnmodifiableView();
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public int getImgUrlsCount() {
        return imgUrls_.size();
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public java.lang.String getImgUrls(int index) {
        return imgUrls_.get(index);
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public com.google.protobuf.ByteString
          getImgUrlsBytes(int index) {
        return imgUrls_.getByteString(index);
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public Builder setImgUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgUrlsIsMutable();
        imgUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public Builder addImgUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgUrlsIsMutable();
        imgUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public Builder addAllImgUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureImgUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, imgUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public Builder clearImgUrls() {
        imgUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string imgUrls = 5;</code>
       */
      public Builder addImgUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImgUrlsIsMutable();
        imgUrls_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eshop.api.product.ProductSubType)
    }

    // @@protoc_insertion_point(class_scope:eshop.api.product.ProductSubType)
    private static final eshop.api.product.Products.ProductSubType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eshop.api.product.Products.ProductSubType();
    }

    public static eshop.api.product.Products.ProductSubType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductSubType>
        PARSER = new com.google.protobuf.AbstractParser<ProductSubType>() {
      @java.lang.Override
      public ProductSubType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductSubType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductSubType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductSubType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eshop.api.product.Products.ProductSubType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eshop_api_product_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eshop_api_product_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eshop_api_product_ProductSubType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eshop_api_product_ProductSubType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Products.proto\022\021eshop.api.product\"\206\001\n\007" +
      "Product\022\n\n\002id\030\001 \001(\t\022\020\n\010vendorId\030\002 \001(\t\022\014\n" +
      "\004name\030\003 \001(\t\022\014\n\004desc\030\004 \001(\t\022\014\n\004tags\030\005 \003(\t\022" +
      "3\n\010subTypes\030\006 \003(\0132!.eshop.api.product.Pr" +
      "oductSubType\"\\\n\016ProductSubType\022\n\n\002id\030\001 \001" +
      "(\t\022\021\n\tproductId\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\014\n\004d" +
      "esc\030\004 \001(\t\022\017\n\007imgUrls\030\005 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eshop_api_product_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eshop_api_product_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eshop_api_product_Product_descriptor,
        new java.lang.String[] { "Id", "VendorId", "Name", "Desc", "Tags", "SubTypes", });
    internal_static_eshop_api_product_ProductSubType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eshop_api_product_ProductSubType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eshop_api_product_ProductSubType_descriptor,
        new java.lang.String[] { "Id", "ProductId", "Name", "Desc", "ImgUrls", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
