// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reviews.proto

package eshop.api.product;

public final class Reviews {
  private Reviews() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code eshop.api.product.Rating}
   */
  public enum Rating
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STAR_1 = 0;</code>
     */
    STAR_1(0),
    /**
     * <code>STAR_2 = 1;</code>
     */
    STAR_2(1),
    /**
     * <code>STAR_3 = 2;</code>
     */
    STAR_3(2),
    /**
     * <code>STAR_4 = 3;</code>
     */
    STAR_4(3),
    /**
     * <code>STAR_5 = 4;</code>
     */
    STAR_5(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STAR_1 = 0;</code>
     */
    public static final int STAR_1_VALUE = 0;
    /**
     * <code>STAR_2 = 1;</code>
     */
    public static final int STAR_2_VALUE = 1;
    /**
     * <code>STAR_3 = 2;</code>
     */
    public static final int STAR_3_VALUE = 2;
    /**
     * <code>STAR_4 = 3;</code>
     */
    public static final int STAR_4_VALUE = 3;
    /**
     * <code>STAR_5 = 4;</code>
     */
    public static final int STAR_5_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Rating valueOf(int value) {
      return forNumber(value);
    }

    public static Rating forNumber(int value) {
      switch (value) {
        case 0: return STAR_1;
        case 1: return STAR_2;
        case 2: return STAR_3;
        case 3: return STAR_4;
        case 4: return STAR_5;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Rating>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Rating> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Rating>() {
            public Rating findValueByNumber(int number) {
              return Rating.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return eshop.api.product.Reviews.getDescriptor().getEnumTypes().get(0);
    }

    private static final Rating[] VALUES = values();

    public static Rating valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Rating(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:eshop.api.product.Rating)
  }

  public interface ReviewOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eshop.api.product.Review)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string productId = 2;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>string productId = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>string subTypeId = 3;</code>
     */
    java.lang.String getSubTypeId();
    /**
     * <code>string subTypeId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubTypeIdBytes();

    /**
     * <code>string comments = 4;</code>
     */
    java.lang.String getComments();
    /**
     * <code>string comments = 4;</code>
     */
    com.google.protobuf.ByteString
        getCommentsBytes();

    /**
     * <code>.eshop.api.product.Rating productRating = 5;</code>
     */
    int getProductRatingValue();
    /**
     * <code>.eshop.api.product.Rating productRating = 5;</code>
     */
    eshop.api.product.Reviews.Rating getProductRating();

    /**
     * <code>.eshop.api.product.Rating deliverRating = 6;</code>
     */
    int getDeliverRatingValue();
    /**
     * <code>.eshop.api.product.Rating deliverRating = 6;</code>
     */
    eshop.api.product.Reviews.Rating getDeliverRating();
  }
  /**
   * Protobuf type {@code eshop.api.product.Review}
   */
  public  static final class Review extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eshop.api.product.Review)
      ReviewOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Review.newBuilder() to construct.
    private Review(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Review() {
      userId_ = "";
      productId_ = "";
      subTypeId_ = "";
      comments_ = "";
      productRating_ = 0;
      deliverRating_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Review(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              subTypeId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              comments_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              productRating_ = rawValue;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              deliverRating_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eshop.api.product.Reviews.internal_static_eshop_api_product_Review_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eshop.api.product.Reviews.internal_static_eshop_api_product_Review_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eshop.api.product.Reviews.Review.class, eshop.api.product.Reviews.Review.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object productId_;
    /**
     * <code>string productId = 2;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string productId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBTYPEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object subTypeId_;
    /**
     * <code>string subTypeId = 3;</code>
     */
    public java.lang.String getSubTypeId() {
      java.lang.Object ref = subTypeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subTypeId_ = s;
        return s;
      }
    }
    /**
     * <code>string subTypeId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubTypeIdBytes() {
      java.lang.Object ref = subTypeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTS_FIELD_NUMBER = 4;
    private volatile java.lang.Object comments_;
    /**
     * <code>string comments = 4;</code>
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      }
    }
    /**
     * <code>string comments = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTRATING_FIELD_NUMBER = 5;
    private int productRating_;
    /**
     * <code>.eshop.api.product.Rating productRating = 5;</code>
     */
    public int getProductRatingValue() {
      return productRating_;
    }
    /**
     * <code>.eshop.api.product.Rating productRating = 5;</code>
     */
    public eshop.api.product.Reviews.Rating getProductRating() {
      @SuppressWarnings("deprecation")
      eshop.api.product.Reviews.Rating result = eshop.api.product.Reviews.Rating.valueOf(productRating_);
      return result == null ? eshop.api.product.Reviews.Rating.UNRECOGNIZED : result;
    }

    public static final int DELIVERRATING_FIELD_NUMBER = 6;
    private int deliverRating_;
    /**
     * <code>.eshop.api.product.Rating deliverRating = 6;</code>
     */
    public int getDeliverRatingValue() {
      return deliverRating_;
    }
    /**
     * <code>.eshop.api.product.Rating deliverRating = 6;</code>
     */
    public eshop.api.product.Reviews.Rating getDeliverRating() {
      @SuppressWarnings("deprecation")
      eshop.api.product.Reviews.Rating result = eshop.api.product.Reviews.Rating.valueOf(deliverRating_);
      return result == null ? eshop.api.product.Reviews.Rating.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_);
      }
      if (!getSubTypeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subTypeId_);
      }
      if (!getCommentsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, comments_);
      }
      if (productRating_ != eshop.api.product.Reviews.Rating.STAR_1.getNumber()) {
        output.writeEnum(5, productRating_);
      }
      if (deliverRating_ != eshop.api.product.Reviews.Rating.STAR_1.getNumber()) {
        output.writeEnum(6, deliverRating_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productId_);
      }
      if (!getSubTypeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subTypeId_);
      }
      if (!getCommentsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, comments_);
      }
      if (productRating_ != eshop.api.product.Reviews.Rating.STAR_1.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, productRating_);
      }
      if (deliverRating_ != eshop.api.product.Reviews.Rating.STAR_1.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, deliverRating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eshop.api.product.Reviews.Review)) {
        return super.equals(obj);
      }
      eshop.api.product.Reviews.Review other = (eshop.api.product.Reviews.Review) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && getSubTypeId()
          .equals(other.getSubTypeId());
      result = result && getComments()
          .equals(other.getComments());
      result = result && productRating_ == other.productRating_;
      result = result && deliverRating_ == other.deliverRating_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + SUBTYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getSubTypeId().hashCode();
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
      hash = (37 * hash) + PRODUCTRATING_FIELD_NUMBER;
      hash = (53 * hash) + productRating_;
      hash = (37 * hash) + DELIVERRATING_FIELD_NUMBER;
      hash = (53 * hash) + deliverRating_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eshop.api.product.Reviews.Review parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Reviews.Review parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.product.Reviews.Review parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Reviews.Review parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eshop.api.product.Reviews.Review parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.product.Reviews.Review parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eshop.api.product.Reviews.Review prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eshop.api.product.Review}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eshop.api.product.Review)
        eshop.api.product.Reviews.ReviewOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eshop.api.product.Reviews.internal_static_eshop_api_product_Review_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eshop.api.product.Reviews.internal_static_eshop_api_product_Review_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eshop.api.product.Reviews.Review.class, eshop.api.product.Reviews.Review.Builder.class);
      }

      // Construct using eshop.api.product.Reviews.Review.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        productId_ = "";

        subTypeId_ = "";

        comments_ = "";

        productRating_ = 0;

        deliverRating_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eshop.api.product.Reviews.internal_static_eshop_api_product_Review_descriptor;
      }

      @java.lang.Override
      public eshop.api.product.Reviews.Review getDefaultInstanceForType() {
        return eshop.api.product.Reviews.Review.getDefaultInstance();
      }

      @java.lang.Override
      public eshop.api.product.Reviews.Review build() {
        eshop.api.product.Reviews.Review result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eshop.api.product.Reviews.Review buildPartial() {
        eshop.api.product.Reviews.Review result = new eshop.api.product.Reviews.Review(this);
        result.userId_ = userId_;
        result.productId_ = productId_;
        result.subTypeId_ = subTypeId_;
        result.comments_ = comments_;
        result.productRating_ = productRating_;
        result.deliverRating_ = deliverRating_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eshop.api.product.Reviews.Review) {
          return mergeFrom((eshop.api.product.Reviews.Review)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eshop.api.product.Reviews.Review other) {
        if (other == eshop.api.product.Reviews.Review.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        if (!other.getSubTypeId().isEmpty()) {
          subTypeId_ = other.subTypeId_;
          onChanged();
        }
        if (!other.getComments().isEmpty()) {
          comments_ = other.comments_;
          onChanged();
        }
        if (other.productRating_ != 0) {
          setProductRatingValue(other.getProductRatingValue());
        }
        if (other.deliverRating_ != 0) {
          setDeliverRatingValue(other.getDeliverRatingValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eshop.api.product.Reviews.Review parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eshop.api.product.Reviews.Review) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string productId = 2;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 2;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subTypeId_ = "";
      /**
       * <code>string subTypeId = 3;</code>
       */
      public java.lang.String getSubTypeId() {
        java.lang.Object ref = subTypeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subTypeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subTypeId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubTypeIdBytes() {
        java.lang.Object ref = subTypeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subTypeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subTypeId = 3;</code>
       */
      public Builder setSubTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subTypeId = 3;</code>
       */
      public Builder clearSubTypeId() {
        
        subTypeId_ = getDefaultInstance().getSubTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>string subTypeId = 3;</code>
       */
      public Builder setSubTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subTypeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object comments_ = "";
      /**
       * <code>string comments = 4;</code>
       */
      public java.lang.String getComments() {
        java.lang.Object ref = comments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comments_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string comments = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCommentsBytes() {
        java.lang.Object ref = comments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comments = 4;</code>
       */
      public Builder setComments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string comments = 4;</code>
       */
      public Builder clearComments() {
        
        comments_ = getDefaultInstance().getComments();
        onChanged();
        return this;
      }
      /**
       * <code>string comments = 4;</code>
       */
      public Builder setCommentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comments_ = value;
        onChanged();
        return this;
      }

      private int productRating_ = 0;
      /**
       * <code>.eshop.api.product.Rating productRating = 5;</code>
       */
      public int getProductRatingValue() {
        return productRating_;
      }
      /**
       * <code>.eshop.api.product.Rating productRating = 5;</code>
       */
      public Builder setProductRatingValue(int value) {
        productRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.product.Rating productRating = 5;</code>
       */
      public eshop.api.product.Reviews.Rating getProductRating() {
        @SuppressWarnings("deprecation")
        eshop.api.product.Reviews.Rating result = eshop.api.product.Reviews.Rating.valueOf(productRating_);
        return result == null ? eshop.api.product.Reviews.Rating.UNRECOGNIZED : result;
      }
      /**
       * <code>.eshop.api.product.Rating productRating = 5;</code>
       */
      public Builder setProductRating(eshop.api.product.Reviews.Rating value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        productRating_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.product.Rating productRating = 5;</code>
       */
      public Builder clearProductRating() {
        
        productRating_ = 0;
        onChanged();
        return this;
      }

      private int deliverRating_ = 0;
      /**
       * <code>.eshop.api.product.Rating deliverRating = 6;</code>
       */
      public int getDeliverRatingValue() {
        return deliverRating_;
      }
      /**
       * <code>.eshop.api.product.Rating deliverRating = 6;</code>
       */
      public Builder setDeliverRatingValue(int value) {
        deliverRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.product.Rating deliverRating = 6;</code>
       */
      public eshop.api.product.Reviews.Rating getDeliverRating() {
        @SuppressWarnings("deprecation")
        eshop.api.product.Reviews.Rating result = eshop.api.product.Reviews.Rating.valueOf(deliverRating_);
        return result == null ? eshop.api.product.Reviews.Rating.UNRECOGNIZED : result;
      }
      /**
       * <code>.eshop.api.product.Rating deliverRating = 6;</code>
       */
      public Builder setDeliverRating(eshop.api.product.Reviews.Rating value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        deliverRating_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.product.Rating deliverRating = 6;</code>
       */
      public Builder clearDeliverRating() {
        
        deliverRating_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eshop.api.product.Review)
    }

    // @@protoc_insertion_point(class_scope:eshop.api.product.Review)
    private static final eshop.api.product.Reviews.Review DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eshop.api.product.Reviews.Review();
    }

    public static eshop.api.product.Reviews.Review getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Review>
        PARSER = new com.google.protobuf.AbstractParser<Review>() {
      @java.lang.Override
      public Review parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Review(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Review> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Review> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eshop.api.product.Reviews.Review getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eshop_api_product_Review_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eshop_api_product_Review_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rReviews.proto\022\021eshop.api.product\"\264\001\n\006R" +
      "eview\022\016\n\006userId\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t" +
      "\022\021\n\tsubTypeId\030\003 \001(\t\022\020\n\010comments\030\004 \001(\t\0220\n" +
      "\rproductRating\030\005 \001(\0162\031.eshop.api.product" +
      ".Rating\0220\n\rdeliverRating\030\006 \001(\0162\031.eshop.a" +
      "pi.product.Rating*D\n\006Rating\022\n\n\006STAR_1\020\000\022" +
      "\n\n\006STAR_2\020\001\022\n\n\006STAR_3\020\002\022\n\n\006STAR_4\020\003\022\n\n\006S" +
      "TAR_5\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eshop_api_product_Review_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eshop_api_product_Review_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eshop_api_product_Review_descriptor,
        new java.lang.String[] { "UserId", "ProductId", "SubTypeId", "Comments", "ProductRating", "DeliverRating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
