// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Prices.proto

package eshop.api.pricing;

public final class Prices {
  private Prices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PriceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eshop.api.pricing.Price)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string productId = 1;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>string productId = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>string subTypeId = 2;</code>
     */
    java.lang.String getSubTypeId();
    /**
     * <code>string subTypeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubTypeIdBytes();

    /**
     * <code>double fullPrice = 3;</code>
     */
    double getFullPrice();

    /**
     * <code>double salePrice = 4;</code>
     */
    double getSalePrice();

    /**
     * <code>int64 saleStart = 5;</code>
     */
    long getSaleStart();

    /**
     * <code>int64 saleUntil = 6;</code>
     */
    long getSaleUntil();
  }
  /**
   * Protobuf type {@code eshop.api.pricing.Price}
   */
  public  static final class Price extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eshop.api.pricing.Price)
      PriceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Price.newBuilder() to construct.
    private Price(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Price() {
      productId_ = "";
      subTypeId_ = "";
      fullPrice_ = 0D;
      salePrice_ = 0D;
      saleStart_ = 0L;
      saleUntil_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Price(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              subTypeId_ = s;
              break;
            }
            case 25: {

              fullPrice_ = input.readDouble();
              break;
            }
            case 33: {

              salePrice_ = input.readDouble();
              break;
            }
            case 40: {

              saleStart_ = input.readInt64();
              break;
            }
            case 48: {

              saleUntil_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eshop.api.pricing.Prices.internal_static_eshop_api_pricing_Price_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eshop.api.pricing.Prices.internal_static_eshop_api_pricing_Price_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eshop.api.pricing.Prices.Price.class, eshop.api.pricing.Prices.Price.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object productId_;
    /**
     * <code>string productId = 1;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string productId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBTYPEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object subTypeId_;
    /**
     * <code>string subTypeId = 2;</code>
     */
    public java.lang.String getSubTypeId() {
      java.lang.Object ref = subTypeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subTypeId_ = s;
        return s;
      }
    }
    /**
     * <code>string subTypeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubTypeIdBytes() {
      java.lang.Object ref = subTypeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULLPRICE_FIELD_NUMBER = 3;
    private double fullPrice_;
    /**
     * <code>double fullPrice = 3;</code>
     */
    public double getFullPrice() {
      return fullPrice_;
    }

    public static final int SALEPRICE_FIELD_NUMBER = 4;
    private double salePrice_;
    /**
     * <code>double salePrice = 4;</code>
     */
    public double getSalePrice() {
      return salePrice_;
    }

    public static final int SALESTART_FIELD_NUMBER = 5;
    private long saleStart_;
    /**
     * <code>int64 saleStart = 5;</code>
     */
    public long getSaleStart() {
      return saleStart_;
    }

    public static final int SALEUNTIL_FIELD_NUMBER = 6;
    private long saleUntil_;
    /**
     * <code>int64 saleUntil = 6;</code>
     */
    public long getSaleUntil() {
      return saleUntil_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productId_);
      }
      if (!getSubTypeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subTypeId_);
      }
      if (fullPrice_ != 0D) {
        output.writeDouble(3, fullPrice_);
      }
      if (salePrice_ != 0D) {
        output.writeDouble(4, salePrice_);
      }
      if (saleStart_ != 0L) {
        output.writeInt64(5, saleStart_);
      }
      if (saleUntil_ != 0L) {
        output.writeInt64(6, saleUntil_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productId_);
      }
      if (!getSubTypeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subTypeId_);
      }
      if (fullPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fullPrice_);
      }
      if (salePrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salePrice_);
      }
      if (saleStart_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, saleStart_);
      }
      if (saleUntil_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, saleUntil_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eshop.api.pricing.Prices.Price)) {
        return super.equals(obj);
      }
      eshop.api.pricing.Prices.Price other = (eshop.api.pricing.Prices.Price) obj;

      boolean result = true;
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && getSubTypeId()
          .equals(other.getSubTypeId());
      result = result && (
          java.lang.Double.doubleToLongBits(getFullPrice())
          == java.lang.Double.doubleToLongBits(
              other.getFullPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getSalePrice())
          == java.lang.Double.doubleToLongBits(
              other.getSalePrice()));
      result = result && (getSaleStart()
          == other.getSaleStart());
      result = result && (getSaleUntil()
          == other.getSaleUntil());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + SUBTYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getSubTypeId().hashCode();
      hash = (37 * hash) + FULLPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFullPrice()));
      hash = (37 * hash) + SALEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalePrice()));
      hash = (37 * hash) + SALESTART_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSaleStart());
      hash = (37 * hash) + SALEUNTIL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSaleUntil());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eshop.api.pricing.Prices.Price parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.pricing.Prices.Price parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eshop.api.pricing.Prices.Price parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.pricing.Prices.Price parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eshop.api.pricing.Prices.Price prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eshop.api.pricing.Price}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eshop.api.pricing.Price)
        eshop.api.pricing.Prices.PriceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eshop.api.pricing.Prices.internal_static_eshop_api_pricing_Price_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eshop.api.pricing.Prices.internal_static_eshop_api_pricing_Price_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eshop.api.pricing.Prices.Price.class, eshop.api.pricing.Prices.Price.Builder.class);
      }

      // Construct using eshop.api.pricing.Prices.Price.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productId_ = "";

        subTypeId_ = "";

        fullPrice_ = 0D;

        salePrice_ = 0D;

        saleStart_ = 0L;

        saleUntil_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eshop.api.pricing.Prices.internal_static_eshop_api_pricing_Price_descriptor;
      }

      @java.lang.Override
      public eshop.api.pricing.Prices.Price getDefaultInstanceForType() {
        return eshop.api.pricing.Prices.Price.getDefaultInstance();
      }

      @java.lang.Override
      public eshop.api.pricing.Prices.Price build() {
        eshop.api.pricing.Prices.Price result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eshop.api.pricing.Prices.Price buildPartial() {
        eshop.api.pricing.Prices.Price result = new eshop.api.pricing.Prices.Price(this);
        result.productId_ = productId_;
        result.subTypeId_ = subTypeId_;
        result.fullPrice_ = fullPrice_;
        result.salePrice_ = salePrice_;
        result.saleStart_ = saleStart_;
        result.saleUntil_ = saleUntil_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eshop.api.pricing.Prices.Price) {
          return mergeFrom((eshop.api.pricing.Prices.Price)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eshop.api.pricing.Prices.Price other) {
        if (other == eshop.api.pricing.Prices.Price.getDefaultInstance()) return this;
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        if (!other.getSubTypeId().isEmpty()) {
          subTypeId_ = other.subTypeId_;
          onChanged();
        }
        if (other.getFullPrice() != 0D) {
          setFullPrice(other.getFullPrice());
        }
        if (other.getSalePrice() != 0D) {
          setSalePrice(other.getSalePrice());
        }
        if (other.getSaleStart() != 0L) {
          setSaleStart(other.getSaleStart());
        }
        if (other.getSaleUntil() != 0L) {
          setSaleUntil(other.getSaleUntil());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eshop.api.pricing.Prices.Price parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eshop.api.pricing.Prices.Price) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string productId = 1;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productId = 1;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 1;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 1;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subTypeId_ = "";
      /**
       * <code>string subTypeId = 2;</code>
       */
      public java.lang.String getSubTypeId() {
        java.lang.Object ref = subTypeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subTypeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subTypeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubTypeIdBytes() {
        java.lang.Object ref = subTypeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subTypeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subTypeId = 2;</code>
       */
      public Builder setSubTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subTypeId = 2;</code>
       */
      public Builder clearSubTypeId() {
        
        subTypeId_ = getDefaultInstance().getSubTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>string subTypeId = 2;</code>
       */
      public Builder setSubTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subTypeId_ = value;
        onChanged();
        return this;
      }

      private double fullPrice_ ;
      /**
       * <code>double fullPrice = 3;</code>
       */
      public double getFullPrice() {
        return fullPrice_;
      }
      /**
       * <code>double fullPrice = 3;</code>
       */
      public Builder setFullPrice(double value) {
        
        fullPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double fullPrice = 3;</code>
       */
      public Builder clearFullPrice() {
        
        fullPrice_ = 0D;
        onChanged();
        return this;
      }

      private double salePrice_ ;
      /**
       * <code>double salePrice = 4;</code>
       */
      public double getSalePrice() {
        return salePrice_;
      }
      /**
       * <code>double salePrice = 4;</code>
       */
      public Builder setSalePrice(double value) {
        
        salePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double salePrice = 4;</code>
       */
      public Builder clearSalePrice() {
        
        salePrice_ = 0D;
        onChanged();
        return this;
      }

      private long saleStart_ ;
      /**
       * <code>int64 saleStart = 5;</code>
       */
      public long getSaleStart() {
        return saleStart_;
      }
      /**
       * <code>int64 saleStart = 5;</code>
       */
      public Builder setSaleStart(long value) {
        
        saleStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 saleStart = 5;</code>
       */
      public Builder clearSaleStart() {
        
        saleStart_ = 0L;
        onChanged();
        return this;
      }

      private long saleUntil_ ;
      /**
       * <code>int64 saleUntil = 6;</code>
       */
      public long getSaleUntil() {
        return saleUntil_;
      }
      /**
       * <code>int64 saleUntil = 6;</code>
       */
      public Builder setSaleUntil(long value) {
        
        saleUntil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 saleUntil = 6;</code>
       */
      public Builder clearSaleUntil() {
        
        saleUntil_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eshop.api.pricing.Price)
    }

    // @@protoc_insertion_point(class_scope:eshop.api.pricing.Price)
    private static final eshop.api.pricing.Prices.Price DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eshop.api.pricing.Prices.Price();
    }

    public static eshop.api.pricing.Prices.Price getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Price>
        PARSER = new com.google.protobuf.AbstractParser<Price>() {
      @java.lang.Override
      public Price parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Price(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Price> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Price> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eshop.api.pricing.Prices.Price getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eshop_api_pricing_Price_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eshop_api_pricing_Price_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Prices.proto\022\021eshop.api.pricing\"y\n\005Pri" +
      "ce\022\021\n\tproductId\030\001 \001(\t\022\021\n\tsubTypeId\030\002 \001(\t" +
      "\022\021\n\tfullPrice\030\003 \001(\001\022\021\n\tsalePrice\030\004 \001(\001\022\021" +
      "\n\tsaleStart\030\005 \001(\003\022\021\n\tsaleUntil\030\006 \001(\003b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eshop_api_pricing_Price_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eshop_api_pricing_Price_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eshop_api_pricing_Price_descriptor,
        new java.lang.String[] { "ProductId", "SubTypeId", "FullPrice", "SalePrice", "SaleStart", "SaleUntil", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
