// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Orders.proto

package eshop.api.ordering;

public final class Orders {
  private Orders() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code eshop.api.ordering.OrderStatus}
   */
  public enum OrderStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PENDING = 0;</code>
     */
    PENDING(0),
    /**
     * <code>CONFIRMED = 1;</code>
     */
    CONFIRMED(1),
    /**
     * <code>SHIPPED = 2;</code>
     */
    SHIPPED(2),
    /**
     * <code>DELIVERED = 3;</code>
     */
    DELIVERED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PENDING = 0;</code>
     */
    public static final int PENDING_VALUE = 0;
    /**
     * <code>CONFIRMED = 1;</code>
     */
    public static final int CONFIRMED_VALUE = 1;
    /**
     * <code>SHIPPED = 2;</code>
     */
    public static final int SHIPPED_VALUE = 2;
    /**
     * <code>DELIVERED = 3;</code>
     */
    public static final int DELIVERED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderStatus valueOf(int value) {
      return forNumber(value);
    }

    public static OrderStatus forNumber(int value) {
      switch (value) {
        case 0: return PENDING;
        case 1: return CONFIRMED;
        case 2: return SHIPPED;
        case 3: return DELIVERED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderStatus>() {
            public OrderStatus findValueByNumber(int number) {
              return OrderStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return eshop.api.ordering.Orders.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrderStatus[] VALUES = values();

    public static OrderStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:eshop.api.ordering.OrderStatus)
  }

  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eshop.api.ordering.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string customerId = 2;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>string customerId = 2;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <code>string productId = 3;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>string productId = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>int32 quantity = 4;</code>
     */
    int getQuantity();

    /**
     * <code>string shippingAddress = 5;</code>
     */
    java.lang.String getShippingAddress();
    /**
     * <code>string shippingAddress = 5;</code>
     */
    com.google.protobuf.ByteString
        getShippingAddressBytes();

    /**
     * <code>string billingAddress = 6;</code>
     */
    java.lang.String getBillingAddress();
    /**
     * <code>string billingAddress = 6;</code>
     */
    com.google.protobuf.ByteString
        getBillingAddressBytes();

    /**
     * <code>string comment = 7;</code>
     */
    java.lang.String getComment();
    /**
     * <code>string comment = 7;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <code>int64 createdAt = 8;</code>
     */
    long getCreatedAt();

    /**
     * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
     */
    int getStatusValue();
    /**
     * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
     */
    eshop.api.ordering.Orders.OrderStatus getStatus();
  }
  /**
   * Protobuf type {@code eshop.api.ordering.Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eshop.api.ordering.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      id_ = "";
      customerId_ = "";
      productId_ = "";
      quantity_ = 0;
      shippingAddress_ = "";
      billingAddress_ = "";
      comment_ = "";
      createdAt_ = 0L;
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              customerId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            case 32: {

              quantity_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              shippingAddress_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              billingAddress_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              comment_ = s;
              break;
            }
            case 64: {

              createdAt_ = input.readInt64();
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eshop.api.ordering.Orders.internal_static_eshop_api_ordering_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eshop.api.ordering.Orders.internal_static_eshop_api_ordering_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eshop.api.ordering.Orders.Order.class, eshop.api.ordering.Orders.Order.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object customerId_;
    /**
     * <code>string customerId = 2;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <code>string customerId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object productId_;
    /**
     * <code>string productId = 3;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string productId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    private int quantity_;
    /**
     * <code>int32 quantity = 4;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int SHIPPINGADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object shippingAddress_;
    /**
     * <code>string shippingAddress = 5;</code>
     */
    public java.lang.String getShippingAddress() {
      java.lang.Object ref = shippingAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shippingAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string shippingAddress = 5;</code>
     */
    public com.google.protobuf.ByteString
        getShippingAddressBytes() {
      java.lang.Object ref = shippingAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shippingAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BILLINGADDRESS_FIELD_NUMBER = 6;
    private volatile java.lang.Object billingAddress_;
    /**
     * <code>string billingAddress = 6;</code>
     */
    public java.lang.String getBillingAddress() {
      java.lang.Object ref = billingAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billingAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string billingAddress = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBillingAddressBytes() {
      java.lang.Object ref = billingAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billingAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENT_FIELD_NUMBER = 7;
    private volatile java.lang.Object comment_;
    /**
     * <code>string comment = 7;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <code>string comment = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDAT_FIELD_NUMBER = 8;
    private long createdAt_;
    /**
     * <code>int64 createdAt = 8;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    private int status_;
    /**
     * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
     */
    public eshop.api.ordering.Orders.OrderStatus getStatus() {
      @SuppressWarnings("deprecation")
      eshop.api.ordering.Orders.OrderStatus result = eshop.api.ordering.Orders.OrderStatus.valueOf(status_);
      return result == null ? eshop.api.ordering.Orders.OrderStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productId_);
      }
      if (quantity_ != 0) {
        output.writeInt32(4, quantity_);
      }
      if (!getShippingAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, shippingAddress_);
      }
      if (!getBillingAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, billingAddress_);
      }
      if (!getCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, comment_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(8, createdAt_);
      }
      if (status_ != eshop.api.ordering.Orders.OrderStatus.PENDING.getNumber()) {
        output.writeEnum(9, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerId_);
      }
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productId_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, quantity_);
      }
      if (!getShippingAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, shippingAddress_);
      }
      if (!getBillingAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, billingAddress_);
      }
      if (!getCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, comment_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, createdAt_);
      }
      if (status_ != eshop.api.ordering.Orders.OrderStatus.PENDING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eshop.api.ordering.Orders.Order)) {
        return super.equals(obj);
      }
      eshop.api.ordering.Orders.Order other = (eshop.api.ordering.Orders.Order) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getCustomerId()
          .equals(other.getCustomerId());
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && (getQuantity()
          == other.getQuantity());
      result = result && getShippingAddress()
          .equals(other.getShippingAddress());
      result = result && getBillingAddress()
          .equals(other.getBillingAddress());
      result = result && getComment()
          .equals(other.getComment());
      result = result && (getCreatedAt()
          == other.getCreatedAt());
      result = result && status_ == other.status_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + SHIPPINGADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getShippingAddress().hashCode();
      hash = (37 * hash) + BILLINGADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getBillingAddress().hashCode();
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedAt());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eshop.api.ordering.Orders.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.ordering.Orders.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eshop.api.ordering.Orders.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eshop.api.ordering.Orders.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eshop.api.ordering.Orders.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eshop.api.ordering.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eshop.api.ordering.Order)
        eshop.api.ordering.Orders.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eshop.api.ordering.Orders.internal_static_eshop_api_ordering_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eshop.api.ordering.Orders.internal_static_eshop_api_ordering_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eshop.api.ordering.Orders.Order.class, eshop.api.ordering.Orders.Order.Builder.class);
      }

      // Construct using eshop.api.ordering.Orders.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        customerId_ = "";

        productId_ = "";

        quantity_ = 0;

        shippingAddress_ = "";

        billingAddress_ = "";

        comment_ = "";

        createdAt_ = 0L;

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eshop.api.ordering.Orders.internal_static_eshop_api_ordering_Order_descriptor;
      }

      @java.lang.Override
      public eshop.api.ordering.Orders.Order getDefaultInstanceForType() {
        return eshop.api.ordering.Orders.Order.getDefaultInstance();
      }

      @java.lang.Override
      public eshop.api.ordering.Orders.Order build() {
        eshop.api.ordering.Orders.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public eshop.api.ordering.Orders.Order buildPartial() {
        eshop.api.ordering.Orders.Order result = new eshop.api.ordering.Orders.Order(this);
        result.id_ = id_;
        result.customerId_ = customerId_;
        result.productId_ = productId_;
        result.quantity_ = quantity_;
        result.shippingAddress_ = shippingAddress_;
        result.billingAddress_ = billingAddress_;
        result.comment_ = comment_;
        result.createdAt_ = createdAt_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eshop.api.ordering.Orders.Order) {
          return mergeFrom((eshop.api.ordering.Orders.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eshop.api.ordering.Orders.Order other) {
        if (other == eshop.api.ordering.Orders.Order.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          onChanged();
        }
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (!other.getShippingAddress().isEmpty()) {
          shippingAddress_ = other.shippingAddress_;
          onChanged();
        }
        if (!other.getBillingAddress().isEmpty()) {
          billingAddress_ = other.billingAddress_;
          onChanged();
        }
        if (!other.getComment().isEmpty()) {
          comment_ = other.comment_;
          onChanged();
        }
        if (other.getCreatedAt() != 0L) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eshop.api.ordering.Orders.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eshop.api.ordering.Orders.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>string customerId = 2;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customerId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customerId = 2;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 2;</code>
       */
      public Builder clearCustomerId() {
        
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 2;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string productId = 3;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productId = 3;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 3;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 3;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 4;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 4;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 4;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object shippingAddress_ = "";
      /**
       * <code>string shippingAddress = 5;</code>
       */
      public java.lang.String getShippingAddress() {
        java.lang.Object ref = shippingAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shippingAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shippingAddress = 5;</code>
       */
      public com.google.protobuf.ByteString
          getShippingAddressBytes() {
        java.lang.Object ref = shippingAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shippingAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shippingAddress = 5;</code>
       */
      public Builder setShippingAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shippingAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shippingAddress = 5;</code>
       */
      public Builder clearShippingAddress() {
        
        shippingAddress_ = getDefaultInstance().getShippingAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string shippingAddress = 5;</code>
       */
      public Builder setShippingAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shippingAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object billingAddress_ = "";
      /**
       * <code>string billingAddress = 6;</code>
       */
      public java.lang.String getBillingAddress() {
        java.lang.Object ref = billingAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          billingAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string billingAddress = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBillingAddressBytes() {
        java.lang.Object ref = billingAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          billingAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string billingAddress = 6;</code>
       */
      public Builder setBillingAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        billingAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string billingAddress = 6;</code>
       */
      public Builder clearBillingAddress() {
        
        billingAddress_ = getDefaultInstance().getBillingAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string billingAddress = 6;</code>
       */
      public Builder setBillingAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        billingAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>string comment = 7;</code>
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string comment = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comment = 7;</code>
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 7;</code>
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 7;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comment_ = value;
        onChanged();
        return this;
      }

      private long createdAt_ ;
      /**
       * <code>int64 createdAt = 8;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>int64 createdAt = 8;</code>
       */
      public Builder setCreatedAt(long value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createdAt = 8;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
       */
      public eshop.api.ordering.Orders.OrderStatus getStatus() {
        @SuppressWarnings("deprecation")
        eshop.api.ordering.Orders.OrderStatus result = eshop.api.ordering.Orders.OrderStatus.valueOf(status_);
        return result == null ? eshop.api.ordering.Orders.OrderStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
       */
      public Builder setStatus(eshop.api.ordering.Orders.OrderStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.eshop.api.ordering.OrderStatus status = 9;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eshop.api.ordering.Order)
    }

    // @@protoc_insertion_point(class_scope:eshop.api.ordering.Order)
    private static final eshop.api.ordering.Orders.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eshop.api.ordering.Orders.Order();
    }

    public static eshop.api.ordering.Orders.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public eshop.api.ordering.Orders.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eshop_api_ordering_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eshop_api_ordering_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Orders.proto\022\022eshop.api.ordering\"\322\001\n\005O" +
      "rder\022\n\n\002id\030\001 \001(\t\022\022\n\ncustomerId\030\002 \001(\t\022\021\n\t" +
      "productId\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\027\n\017shi" +
      "ppingAddress\030\005 \001(\t\022\026\n\016billingAddress\030\006 \001" +
      "(\t\022\017\n\007comment\030\007 \001(\t\022\021\n\tcreatedAt\030\010 \001(\003\022/" +
      "\n\006status\030\t \001(\0162\037.eshop.api.ordering.Orde" +
      "rStatus*E\n\013OrderStatus\022\013\n\007PENDING\020\000\022\r\n\tC" +
      "ONFIRMED\020\001\022\013\n\007SHIPPED\020\002\022\r\n\tDELIVERED\020\003b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eshop_api_ordering_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eshop_api_ordering_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eshop_api_ordering_Order_descriptor,
        new java.lang.String[] { "Id", "CustomerId", "ProductId", "Quantity", "ShippingAddress", "BillingAddress", "Comment", "CreatedAt", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
